import { MenuItem, MenuCategory, RestaurantEvent, GalleryItem } from "@/types";

export const MOCK_CATEGORIES: MenuCategory[] = [
  { id: "starters", name: "Starters & Small Plates", slug: "starters", displayOrder: 1 },
  { id: "mains", name: "Executive Mains", slug: "mains", displayOrder: 2 },
  { id: "grills", name: "Signature Grills", slug: "grills", displayOrder: 3 },
  { id: "desserts", name: "Artisanal Desserts", slug: "desserts", displayOrder: 4 },
  { id: "cocktails", name: "Handcrafted Cocktails", slug: "cocktails", displayOrder: 5 },
  { id: "wines", name: "Cellar Selection", slug: "wines", displayOrder: 6 },
];

export const MOCK_MENU_ITEMS: MenuItem[] = [
  {
    id: "item-1",
    title: "Pan-Seared Diver Scallops",
    description: "Truffle cauliflower puree, crispy pancetta lardons, herb emulsion, gold leaf touch.",
    price: 26,
    currency: "USD",
    categoryId: "starters",
    categoryName: "Starters & Small Plates",
    imageUrl: "https://images.unsplash.com/photo-1532550907401-a500c9a57435?auto=format&fit=crop&w=800&q=80",
    dietaryFlags: ["Gluten-Free", "Chef Special"],
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: "item-2",
    title: "Dry-Aged Prime Ribeye (12oz)",
    description: "45-day aged Black Angus, smoked bone marrow butter, roasted heritage carrots, red wine reduction.",
    price: 48,
    currency: "USD",
    categoryId: "mains",
    categoryName: "Executive Mains",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    dietaryFlags: ["Chef Special"],
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: "item-3",
    title: "Wild Mushroom & Truffle Risotto",
    description: "Carnaroli rice, foraged chanterelles, aged Parmigiano-Reggiano, white truffle oil essence.",
    price: 32,
    currency: "USD",
    categoryId: "mains",
    categoryName: "Executive Mains",
    imageUrl: "https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80",
    dietaryFlags: ["Vegetarian", "Gluten-Free"],
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: "item-4",
    title: "Sokem Golden Old Fashioned",
    description: "Small-batch bourbon, smoked demerara syrup, Angostura & orange bitters, flamed orange peel, 24k gold flake.",
    price: 19,
    currency: "USD",
    categoryId: "cocktails",
    categoryName: "Handcrafted Cocktails",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80",
    dietaryFlags: ["Signature Cocktail"],
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: "item-5",
    title: "Smoked Mezcal Paloma",
    description: "Artisanal mezcal, fresh pink grapefruit, agave nectar, lime, volcanic black salt rim.",
    price: 18,
    currency: "USD",
    categoryId: "cocktails",
    categoryName: "Handcrafted Cocktails",
    imageUrl: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    dietaryFlags: ["Signature Cocktail"],
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: "item-6",
    title: "Valrhona Dark Chocolate Fondant",
    description: "Molten 70% dark chocolate core, pistachio gelato, salted caramel drizzle.",
    price: 16,
    currency: "USD",
    categoryId: "desserts",
    categoryName: "Artisanal Desserts",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    dietaryFlags: ["Vegetarian"],
    isAvailable: true,
    isFeatured: true,
  },
];

export const MOCK_EVENTS: RestaurantEvent[] = [
  {
    id: "event-1",
    title: "Jazz & Gold Cocktail Soirée",
    slug: "jazz-and-gold-soiree",
    description: "Immerse yourself in live acoustic jazz trio performances paired with exclusive cocktail flights and chef canapés.",
    date: "Every Thursday Evening",
    time: "7:30 PM - 11:00 PM",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    badge: "Live Music",
    isPublished: true,
  },
  {
    id: "event-2",
    title: "Executive Chef's Wine & Tasting Dinner",
    slug: "chef-wine-tasting-dinner",
    description: "A 5-course gastronomic journey curated by our executive culinary team, expertly paired with reserve international vintages.",
    date: "First Saturday of the Month",
    time: "6:30 PM & 9:00 PM Seatings",
    imageUrl: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=800&q=80",
    badge: "Special Tasting",
    isPublished: true,
  },
  {
    id: "event-3",
    title: "Golden Hour Sunset Lounge",
    slug: "golden-hour-lounge",
    description: "Unwind after work with curated ambient DJ sets, complimentary tapas bites, and 2-for-1 signature house mixology.",
    date: "Fridays & Saturdays",
    time: "5:00 PM - 7:30 PM",
    imageUrl: "https://images.unsplash.com/photo-1543007630-9710e4a00a20?auto=format&fit=crop&w=800&q=80",
    badge: "Happy Hour",
    isPublished: true,
  },
];

export const MOCK_GALLERY: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Handcrafted Mixology",
    category: "Cocktails",
    imageUrl: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=800&q=80",
    alt: "Smoked luxury cocktail on marble bar",
  },
  {
    id: "gal-2",
    title: "Prime Dry-Aged Ribeye",
    category: "Culinary",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    alt: "Gourmet plated steak with roasted vegetables",
  },
  {
    id: "gal-3",
    title: "The Main Dining Room",
    category: "Ambience",
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80",
    alt: "Warm ambient restaurant lighting and modern seating",
  },
  {
    id: "gal-4",
    title: "Artisanal Dessert Plating",
    category: "Culinary",
    imageUrl: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    alt: "Dark chocolate molten lava cake with gold leaf",
  },
  {
    id: "gal-5",
    title: "Live Jazz Evenings",
    category: "Events",
    imageUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80",
    alt: "Saxophone player during live music night",
  },
  {
    id: "gal-6",
    title: "The Private Lounge",
    category: "Ambience",
    imageUrl: "https://images.unsplash.com/photo-1578474846511-04ba529f0b88?auto=format&fit=crop&w=800&q=80",
    alt: "Intimate private dining and booth tables",
  },
];
